DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=u1690p3749_pdf_form_generator_secure_pdf_editing_system
DB_USER=u1690p3749_user
DB_PASSWORD=x0fR79Nc6moLVbNl
STORAGE_PATH=/workspace/storage
PDF_USER_PASSWORD=Gstr3b-P@ss2026
PDF_OWNER_PASSWORD=Gstr3b-Own3r!2026
